import { Product } from "@/types";
import {
  LandingPageSVG,
  EcommercePageSVG,
  AdminPageSVG,
  CustomPageSVG,
  WebMaintenanceSVG,
} from "@/assets/svg";

export const products: Product[] = [
  {
    nameKey: "productsPage.products.custom.name",
    shortDescriptionKey: "productsPage.products.custom.shortDescription",
    longDescriptionKey: "productsPage.products.custom.longDescription",
    featuresKey: "productsPage.products.custom.features",
    slug: "software-personalizado",
    technologies: ["Vue", "React", "Express", "MongoDB"],
    illustration: CustomPageSVG,
    category: "desarrollo-a-medida",
    priceRange: "productsPage.products.custom.price",
  },
  {
    nameKey: "productsPage.products.landing.name",
    shortDescriptionKey: "productsPage.products.landing.shortDescription",
    longDescriptionKey: "productsPage.products.landing.longDescription",
    featuresKey: "productsPage.products.landing.features",
    slug: "landing-page",
    technologies: ["HTML", "CSS", "JavaScript", "TailwindCSS"],
    illustration: LandingPageSVG,
    category: "servicio",
    priceRange: "productsPage.products.landing.price",
  },
  {
    nameKey: "productsPage.products.maintenance.name",
    shortDescriptionKey: "productsPage.products.maintenance.shortDescription",
    longDescriptionKey: "productsPage.products.maintenance.longDescription",
    featuresKey: "productsPage.products.maintenance.features",
    slug: "mantenimiento-web",
    technologies: ["CI/CD", "Git", "TypeScript"],
    illustration: WebMaintenanceSVG,
    category: "servicio",
    priceRange: "productsPage.products.maintenance.price",
  },
  {
    nameKey: "productsPage.products.ecommerce.name",
    shortDescriptionKey: "productsPage.products.ecommerce.shortDescription",
    longDescriptionKey: "productsPage.products.ecommerce.longDescription",
    featuresKey: "productsPage.products.ecommerce.features",
    slug: "ecommerce",
    technologies: ["Vue", "Nuxt", "Stripe", "Firebase"],
    illustration: EcommercePageSVG,
    category: "servicio",
    priceRange: "productsPage.products.ecommerce.price",
  },
  {
    nameKey: "productsPage.products.admin.name",
    shortDescriptionKey: "productsPage.products.admin.shortDescription",
    longDescriptionKey: "productsPage.products.admin.longDescription",
    featuresKey: "productsPage.products.admin.features",
    slug: "admin-panel",
    technologies: ["React", "Next.js", "Node.js", "PostgreSQL"],
    illustration: AdminPageSVG,
    category: "desarrollo-a-medida",
    priceRange: "productsPage.products.admin.price",
  },
];
